### ISSUE TITLE
Question about torch.distributed.elastic.multiprocessing.errors

### ISSUE THREAD

**Issue by AnjouPry** [hpcaitech/Open-Sora#161]
![image](https://github.com/hpcaitech/Open-Sora/assets/163949944/fd9d1586-41c4-468b-9fbe-f5cbcd7f628b)

**Comment by fenglincong** [comment]
I have the same problem

**Comment by JThh** [comment]
It could happen due to the mismatch of your cuda version and the version of cuda that your installed pytorch supports. Please run `nvcc --version` and `python -c "import torch; print(torch.__version__); print(torch.version.cuda)"` to check if they match. If they already match, you may update the `LD_LIBRARY_PATH` to include cuda libs by `export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH`. Otherwise, please reinstall pytorch via `conda install pytorch torchvision torchaudio pytorch-cuda=YOUR_CUDA_VERSION_HERE -c pytorch -c nvidia`.
