### ISSUE TITLE
How can I inference with multiple cards?Hurry!!!

### ISSUE THREAD

**Issue by Jackie-Li-0228** [hpcaitech/Open-Sora#206]

**Comment by zhengzangw** [comment]
For now, we do not support DDP. But you can use multiple cards for sequence parallelism. Just see [inference](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#inference) instruction.

```bash
torchrun --standalone --nproc_per_node 1 scripts/inference.py configs/opensora/inference/16x512x512.py --ckpt-path OpenSora-v1-HQ-16x512x512.pth --prompt-path ./assets/texts/t2v_samples.txt
```

**Comment by byhteng** [comment]
A possible way is to comment all the distributed related codes of colossal AI in the inference code, set "device_map" to "auto" when loading T5 encoder with vanilla python launch method, where accelerate will automatically be imported to dispatch the model through sequence parallel. Then the other models including vae and stdit could be loaded on rank 0, without trigering OOM.

**Comment by SuibianP** [comment]
@byhteng Thanks for the lead! Would it be possible to run the video inference in parallel on all GPUs, while keeping one single distributed copy of `t5-v1_1-xxl` to avoid OOM? 

My use case is to run inference on 4 Tesla T4 GPUs, each with 16G vRAM. Inference ended up OOM because both `torchrun` and vanilla Python run tried to load `t5-v1_1-xxl` on one single GPU. I have managed to use the `device_map` technique to distribute t5 across GPUs and run the inference to completion.

The video inference phase, however, is still executed on `cuda:0` only while all other GPUs are unused.

While it seems that STDITv3 does not support `device_map` yet (`accelerate` complains about `_no_split_modules` being undefined), I believe it should be possible to just load the entire STDIT model onto each GPU as `torchrun` is doing, but how to do that?
