### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by 23Rj20** [hpcaitech/Open-Sora#256]
Can I use this on Windows system aswell or it is developed just for Linux right now??

**Comment by IMJONEZZ** [comment]
Use WSL2 (Windows Subsystem Linux). Windows is the best Linux machine.

**Comment by 23Rj20** [comment]
I can't use Linux or even WSL so is there a possibility that I can set this up for solely windows system??

**Comment by IMJONEZZ** [comment]
Not currently, because APEX and xformers both have dependencies that are
unresolvable on windows currently. Just wait though, bitsandbytes used to
be non-windows, eventually support will get added.

If you have windows you should be able to set up and use WSL though.

My book: LLMs in Production
30% discount - https://shortener.manning.com/amDJ


Dňa ut 9. 4. 2024 o 20:50 23Rj20 ***@***.***> napísala(a):

**Comment by zhengzangw** [comment]
replicate of #205
