### ISSUE TITLE
关于demo.py的多显卡问题

### ISSUE THREAD

**Issue by 297297297** [hpcaitech/Open-Sora#257]
请问如何实现如推理过程中给出的多显卡同时工作命令--nproc_per_node 2，我现在有俩块RTX4090，但运行demo.py显示显存不足，只有一块起了作用

**Comment by JThh** [comment]
Has the sequence parallelism been enabled? Kindly check if [this line](https://github.com/hpcaitech/Open-Sora/blob/a5afed2fc3f7d14f6f2d1ea81dd90cb8fff92d93/scripts/inference.py#L35) has set the `enable_sequence_parallelism` flag to `True`.

Otherwise, can you switch to smaller models, as illustrated [here](https://github.com/hpcaitech/Open-Sora/blob/main/docs/commands.md).
