### ISSUE TITLE
torch.distributed.elastic.multiprocessing.api

### ISSUE THREAD

**Issue by MrD005** [hpcaitech/Open-Sora#282]
Traceback (most recent call last):
  File "/root/anaconda3/envs/opensora/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/root/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/root/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
scripts/inference.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-16_16:40:07
  host      : e2e-84-47.ssdcloudindia.net
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 28813)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 28813
=======================================================

**Comment by JThh** [comment]
It could be due to the mismatch between cuda and pytorch versions. Run `nvcc --version` and `python -c 'import torch; print(torch.version.cuda);'` to see if they match.

**Comment by erichtho** [comment]
Same error.
and `nvcc --version` matches `python -c 'import torch; print(torch.version.cuda);'`
![截屏2024-04-17 11 16 13](https://github.com/hpcaitech/Open-Sora/assets/30315656/bd08054f-cf40-4c99-b84a-250287f7742c)

**Comment by erichtho** [comment]
> Same error. and `nvcc --version` matches `python -c 'import torch; print(torch.version.cuda);'` ![截屏2024-04-17 11 16 13](https://private-user-images.githubusercontent.com/30315656/323059532-bd08054f-cf40-4c99-b84a-250287f7742c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzg1OTMsIm5iZiI6MTcxMzMzODI5MywicGF0aCI6Ii8zMDMxNTY1Ni8zMjMwNTk1MzItYmQwODA1NGYtY2Y0MC00Yzk5LWI4NGEtMjUwMjg3Zjc3NDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA3MTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZjlkMWVjYjE5ZTI0ZTAzMDJkYTQ5MTE5NWM2M2I2MGI1NDgxMDgzMjZjNjUyYmZhMzc1NjhhODgzNmYyNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TnKT7RXikU_CD5cn8U2bavuaCVkNFuDvRMhCIuL43LI)

also found with dmesg:
<img width="1110" alt="截屏2024-04-17 15 19 03" src="https://github.com/hpcaitech/Open-Sora/assets/30315656/5efeba9b-2aa4-49cb-bb47-881d745eb58d">

**Comment by MrD005** [comment]
same 
`nvcc -v` and `python -c 'import torch; print(torch.version.cuda);'` return same cuda version

11.8
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by erichtho** [comment]
hi, I downgrade torch to 2.1.2 and resolve the problem(also changed xformers version to [v0.0.23.post1](https://github.com/facebookresearch/xformers/releases/tag/v0.0.23.post1)).
here is how I locate problem:
1.debug with pdb, found is torch.nn.Conv3d raise segmentation fault
2.searched and got a known issue, which says it is an oneDNN upgrade issue, pytorch 2.1.2 can work, check: https://github.com/pytorch/pytorch/issues/120406

hope helpful.

**Comment by JThh** [comment]
Thanks for sharing @erichtho . Would this solve your issue as well? @MrD005

**Comment by MrD005** [comment]
thanks it solved the problem

**Comment by reich208github** [comment]
**hi, guys**

**i have installed pakages with editions like these:**

apex                      0.1
torch                     2.1.2+cu121
torchaudio                2.1.2+cu121
torchvision               0.16.2+cu121
xformers                  0.0.23.post1

**my cuda version and pytorch related cuda version are like these:**

(env_open_sora) root@SSWON-X10SRA:/home/SSWON/Open-Sora# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
(env_open_sora) root@SSWON-X10SRA:/home/SSWON/Open-Sora# python
Python 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.version.cuda)
12.1

**but after i run command:**

torchrun --standalone --nproc_per_node 1 scripts/inference.py configs/opensora/inference/16x512x512.py --ckpt-path OpenSora-v1-HQ-16x512x512.pth --prompt-path assets/texts/t2v_samples.txt

**the output get a failure:**

Missing keys: ['pos_embed', 'pos_embed_temporal']
Unexpected keys: []
Traceback (most recent call last):
  File "/home/SSWON/Open-Sora/scripts/inference.py", line 112, in <module>
    main()
  File "/home/SSWON/Open-Sora/scripts/inference.py", line 93, in main
    samples = scheduler.sample(
TypeError: IDDPM.sample() got an unexpected keyword argument 'z_size'
[2024-04-27 10:48:57,792] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 9284) of binary: /root/anaconda3/envs/env_open_sora/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/env_open_sora/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/env_open_sora/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/env_open_sora/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/root/anaconda3/envs/env_open_sora/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/root/anaconda3/envs/env_open_sora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/env_open_sora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scripts/inference.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-27_10:48:57
  host      : SSWON-X10SRA
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 9284)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**is there have someone to help me for this problem?** 

**thanks for your guys**
