### ISSUE TITLE
视频分割偏移问题

### ISSUE THREAD

**Issue by boanz** [hpcaitech/Open-Sora#567]
发现用“python -m tools.scene_cut.cut ${ROOT_META}/xxx.csv --save_dir ${ROOT_CLIPS}”，进行视频分割的时候，分割出来的片段存在偏移。而直接使用scenedetect的split_video_ffmpeg方法，则没有问题。
上述问题会导致镜头不完整，或者跨镜头，不知道这个对训练会不会有什么影响。

**Comment by JThh** [comment]
Thanks for raising your concern. Can @zhengzangw please take a look to see if any action is needed? Thanks!

**Comment by zhengzangw** [comment]
Can @xyupeng please take a look of this?

**Comment by xyupeng** [comment]
Hi @boanz ,

Thank you for pointing out the problem. Yes, the previous code really causes inaccuracy up to 0.5 sec, which is due to fps=1. I have updated the code to set fps=100, which means it will round to two decimal places (i.e., 0.01 sec) and will be much more accurate.
![image](https://github.com/hpcaitech/Open-Sora/assets/99191637/a5d65ecc-43dd-4694-9273-844f088716fb)

**Comment by henbucuoshanghai** [comment]
has it changed from the original scenedetect?

**Comment by zhengzangw** [comment]
The lastest scene_cut has fixed this problem.
