### ISSUE TITLE
[Ask] About Sequential Parallel

### ISSUE THREAD

**Issue by yjhong89** [hpcaitech/Open-Sora#593]
Hi! Thanks for sharing great work!

I have 3 questions.

1. If I enable sequential parallelism option, then model-sharding (along patch dimension) is applied across GPUs ?
2. There are 2 operation for sequential parallel. 
    - [split_forward_gather_backward before forward pass to DiT block](https://github.com/hpcaitech/Open-Sora/blob/bf4d6673af9407650b2ce6250debc2453b82c572/opensora/models/stdit/stdit3.py#L416)
    - [gather_forward_split_backward right before final layer](https://github.com/hpcaitech/Open-Sora/blob/bf4d6673af9407650b2ce6250debc2453b82c572/opensora/models/stdit/stdit3.py#L428)
    - What is difference between those two?
3. Multi-node training is supported ??

Thanks!

**Comment by FrankLeeeee** [comment]
1. Yes
2. The first one is to shard the input along the sequence dimension before feeding it into the transformer blocks, the second one is to gather the sharded tensors along the sequence dimension to recover its original shape so that the model will output a full tensor.
3. Yes, you can use `torchrun` or `colossalai run` to launch multi-node training.

**Comment by yjhong89** [comment]
Thanks!
